import { Route } from '@/types';
import got from '@/utils/got';
import { parseDate } from '@/utils/parse-date';

export const route: Route = {
    path: '/models',
    categories: ['program-update'],
    example: '/civitai/models',
    parameters: {},
    features: {
        requireConfig: false,
        requirePuppeteer: false,
        antiCrawler: false,
        supportBT: false,
        supportPodcast: false,
        supportScihub: false,
        nsfw: true,
    },
    radar: [
        {
            source: ['civitai.com/'],
        },
    ],
    name: 'Latest models',
    maintainers: ['YYSK'],
    handler,
    url: 'civitai.com/',
};

const host = 'https://civitai.red';
const apiBase = 'https://api.yyskweb.com';
const accessKey = process.env.ACCESS_KEY ?? '';

async function handler(ctx) {
    const query = ctx.req.query();
    const searchParams = new URLSearchParams({
        limit: '20',
        sort: 'Newest',
    });
    for (const [key, value] of Object.entries(query)) {
        if (value && key !== 'key') {
            searchParams.set(key, String(value));
        }
    }

    const apiUrl = `${host}/api/v1/models?${searchParams.toString()}`;
    const response = await got({
        method: 'GET',
        url: apiUrl,
    });
    const data = response.data.items || [];

    const items = data.map((item: any) => {
        const latestVersion = item.modelVersions?.[0];
        const author = item.creator?.username || 'Unknown';
        const type = item.type || 'Model';
        const baseModel = latestVersion?.baseModel || '';
        const tags = item.tags || [];

        const showCategory = [`<strong><a href="${host}/user/${author}">@${author}</a></strong>`, `<strong>#${type}</strong>`, baseModel ? `<strong>#${baseModel}</strong>` : '', ...tags.map((t: any) => `#${t}`)].filter(Boolean);

        let mediaHtml = '';
        const mediaItems = latestVersion?.images?.slice(0, 5) || [];
        if (mediaItems.length > 0) {
            const imgTags = mediaItems.map((media: any) => {
                const encodedUrl = encodeURIComponent(media.url);
                const webpUrl = `${apiBase}/mediawebp?name=civitai&id=${item.id}&url=${encodedUrl}&key=${accessKey}`;
                return `<p><img src="${webpUrl}" style="max-width: 100%; height: auto;"></p>`;
            });
            mediaHtml = imgTags.join('');
        }

        const descriptionHtml = `
            <p>${showCategory.join(', ')}</p>
            <hr style="border: none; height: 1px; background-color: #000000;">
            ${mediaHtml}
            <div>${item.description || '<p>作者未提供描述。</p>'}</div>
        `;

        return {
            title: item.name,
            link: `${host}/models/${item.id}`,
            description: descriptionHtml,
            author,
            category: [type, baseModel, ...tags].filter(Boolean),
            pubDate: latestVersion?.publishedAt ? parseDate(latestVersion.publishedAt) : null,
        };
    });

    return {
        title: `Civitai Models - ${searchParams.get('sort')}`,
        link: `${host}/models`,
        description: 'Civitai RSS generated by RSSHub',
        item: items,
    };
}
