import { Route } from '@/types';
import got from '@/utils/got';
import { parseDate } from '@/utils/parse-date';
import { buildMediaWebpUrls } from '@/utils/yysk/tools';

export const route: Route = {
    path: '/models',
    categories: ['program-update'],
    example: '/civitai/models',
    parameters: {},
    features: {
        requireConfig: false,
        requirePuppeteer: false,
        antiCrawler: false,
        supportBT: false,
        supportPodcast: false,
        supportScihub: false,
        nsfw: true,
    },
    radar: [
        {
            source: ['civitai.com/'],
        },
    ],
    name: 'Latest models',
    maintainers: ['YYSK'],
    handler,
    url: 'civitai.com/',
};

const host = 'https://civitai.red';

const baseModelMap: Record<string, string> = {
    'Wan Video 2.2 I2V-A14B': 'Wan2.2 I2V',
    'Wan Video 2.2 T2V-A14B': 'Wan2.2 T2V',
};

async function handler(ctx) {
    const query = ctx.req.query();
    const searchParams = new URLSearchParams({
        nsfw: 'true',
        sort: 'Newest',
        limit: '20',
    });
    for (const [key, value] of Object.entries(query)) {
        if (value && key !== 'key') {
            searchParams.set(key, String(value));
        }
    }

    const apiUrl = `${host}/api/v1/models?${searchParams.toString()}`;
    const response = await got({
        method: 'GET',
        url: apiUrl,
    });
    const data = response.data.items || [];

    const items = data.map((item: any) => {
        const latestVersion = item.modelVersions?.[0];
        const modelId = latestVersion?.id || '';
        const author = item.creator?.username || 'Unknown';
        const type = item.type || 'Model';
        const baseModel = latestVersion?.baseModel || '';
        const displayBaseModel = baseModelMap[baseModel] || baseModel;
        const tags = item.tags || [];

        const authorShow = `<strong><a href="${host}/user/${author}">@${author}</a></strong>`;
        const typeShow = `<strong>#${type}</strong>`;
        const baseModelShow = displayBaseModel ? `<strong>#${displayBaseModel}</strong>` : '';
        const tagsShow = tags.map((t: string) => `<a href="${host}/models?tag=${t}">#${t}</a>`);
        const showCategory = [authorShow, typeShow, baseModelShow, ...tagsShow].filter(Boolean);

        let mediaHtml = '';
        const mediaItems = latestVersion?.images?.slice(0, 5) || [];
        if (mediaItems.length > 0) {
            const mediaUrls = mediaItems.map((media: any) => media.url);
            const webpUrls = buildMediaWebpUrls('civitai', item.id, mediaUrls);
            const imgTags = webpUrls.map((url) => `<p><img src="${url}" style="max-width: 100%; height: auto;"></p>`);
            mediaHtml = imgTags.join('');
        }

        const descriptionHtml = `
            <p>${showCategory.join(', ')}</p>
            <hr style="border: none; height: 1px; background-color: #000000;">
            ${mediaHtml}
            <div>${item.description || '<p>作者未提供描述。</p>'}</div>
        `;

        return {
            title: `${displayBaseModel} | ${item.name}`,
            link: `${host}/models/${item.id}${modelId ? `?modelVersionId=${modelId}` : ''}`,
            description: descriptionHtml,
            author,
            category: [type, displayBaseModel, ...tags].filter(Boolean),
            pubDate: latestVersion?.publishedAt ? parseDate(latestVersion.publishedAt) : null,
        };
    });

    return {
        title: `Civitai Models - ${searchParams.get('sort')}`,
        link: `${host}/models`,
        description: 'Civitai RSS generated by RSSHub',
        item: items,
    };
}
